### ISSUE TITLE
TypeError: Cannot set properties of undefined (setting 'highlight')

### ISSUE THREAD

**Issue by KimhoutSam** [edge-js/edge.adonisjs.com#1]
```cmd

vitepress v1.0.0-alpha.4
failed to start server. error:
 TypeError: Cannot set properties of undefined (setting 'highlight')
    at themeConfig (/home/hytrix/Documents/work/edge.adonisjs.com/.vitepress/config.ts:3964:29)
    at async resolveConfigExtends (file:///home/hytrix/Documents/work/edge.adonisjs.com/node_modules/vitepress/dist/node/serve-05342c3d.js:10525:20)
    at async resolveConfigExtends (file:///home/hytrix/Documents/work/edge.adonisjs.com/node_modules/vitepress/dist/node/serve-05342c3d.js:10527:18)
    at async resolveUserConfig (file:///home/hytrix/Documents/work/edge.adonisjs.com/node_modules/vitepress/dist/node/serve-05342c3d.js:10522:11)
    at async resolveConfig (file:///home/hytrix/Documents/work/edge.adonisjs.com/node_modules/vitepress/dist/node/serve-05342c3d.js:10473:36)
    at async createServer (file:///home/hytrix/Documents/work/edge.adonisjs.com/node_modules/vitepress/dist/node/serve-05342c3d.js:34385:18)
```

**Comment by KimhoutSam** [comment]
i used with yarn sorry
